name: CI

on:
  push:
    branches:
      - wf-test

jobs:
  hotspot-ea:
    name: HotSpot (EA)
    runs-on: ubuntu-18.04
    continue-on-error: true
    steps:
      - name: Testme
        run: |
          echo git@github.com:${{ github.repository }}.git
          echo ${GITHUB_ACTOR}
          echo ${GITHUB_REPOSITORY}