name: CI

on:
  push:
    branches:
      - wf-test

jobs:
  hotspot-ea:
    name: HotSpot (EA)
    runs-on: ubuntu-18.04
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Testme
        run: |
          git status
